---
funktional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету,
    размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - После перезагрузки страницы товары в корзине остаются.
  - После оформления заказа пользователя перенаправляют на страницу оплаты.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой
    и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в
    каталоге.
  - Сайт должен иметь мобильную версию.
non-funktional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Этот сайт должен быть SPA.
implicit:
  - Сайт должен автоматически определять язык интерфейса клиента и менять в
    соответствии с этим язык сайта.
  - Должна быть сортировка по цене товаров.
  - На странице товара можно просмотреть все картинки в увеличенном виде.
  - На сайте должен быть выбор валюты USD/RUB.
  - Пользователь должен иметь возможность фильтровать товары по производителям.
  - Сайт должен быть локализован на русском и английском языках.
  - Для оформления заказа необходима авторизация пользователя.
  - При оформлении заказа выводится список товаров, их количество и общая
    стоимость.
  - После оформления заказа корзина должна очищаться автоматически.
  - Пользователь должен иметь возможность фильтровать товары по наличию.
  - Пользователь должен иметь возможность указывать количество товара при
    добавлении в корзину.
  - На сайте должна быть кнопка сброса всех фильтров.
